### ISSUE TITLE
This tool is not hands free?

### ISSUE THREAD

**Issue by rikhuijzer** [yakGPT/yakGPT#21]
Is it correct that I do have to manually click a button to submit the voice prompt to the system? That sounds non hands-free to me

**Comment by yakGPT** [comment]
Very good point @rikhuijzer :D

**Comment by rikhuijzer** [comment]
If I may make a feature request, I would love a system where I can sit in a chair and talk to GPT without touching anything.

It should be possible already with current technology. Text to speech is the hardest to do it seems because it needs another API too, for example, Azure. Open source text to speech is pretty bad unfortunately

**Comment by janeshchhabra** [comment]
Can probably use whisper for this with the same API key - https://openai.com/research/whisper

**Comment by tluyben** [comment]
> Can probably use whisper for this with the same API key - https://openai.com/research/whisper


It already does; https://github.com/yakGPT/yakGPT/blob/e4d39d9913e664e2ad48eb3eeaf70b9bc862b5c5/stores/ChatStore.ts#L381 that's why the quality is so good. 

What needs to happen is to use the browser audio api to detect something like He Yak! and then 'click the button'. Problem is stopping. You can send chunks to the api until one chunk contains 'stop yak! ' but that seems expensive. So probably better to use the web whisper version to detect the stop and then send it to openai for processing finally.

**Comment by yakGPT** [comment]
Azure STT & TTS just merged. Gives a great free tier & value thereafter. Let me know what you think!

**Comment by MikeStirner** [comment]
I think for many people, the free tier will suffice. But some will need more than about 8 hours per month of TTS. I love the idea of Azure, though! Great pricing and quality voices.

**Comment by MikeStirner** [comment]
But can we somehow use whisper with hands free?
